Pass tags to inventory component
RedHatInsights/drift-frontend pull request #357
Opened 2020-10-06 09:40 UTC by karelhala

2020-10-06 10:54 UTC, karelhala commented
ping @johnsonm325

2020-10-06 20:29 UTC, johnsonm325 requested changes
.

2020-10-06 20:31 UTC, johnsonm325 requested changes
@karelhala I had to do some research on hooks to make sure I understood what was happening. I'll need help testing this. I'm not sure what has to happen to get `GLOBAL_FILTER_UPDATE` to fire off.

2020-10-06 20:31 UTC, johnsonm325 commented on src/App.js
> +            dispatch(actions.setGlobalGilterTags(tags));
Should this be `setGlobalFilterTags`?

2020-10-06 20:31 UTC, johnsonm325 commented on src/SmartComponents/modules/actions.js
> +function setGlobalGilterTags(tags = []) {
`setGlobalFilterTags`?

2020-10-07 07:03 UTC, karelhala commented on src/App.js
> +            dispatch(actions.setGlobalGilterTags(tags));
Yup, good catch!

2020-10-07 07:11 UTC, karelhala commented
@johnsonm325 sure thing! This is to enable the global filter feature, basically allowing users to set (currently) tags that they want the UI to be prefiltered by for all applications. If you want to see the global filter on local development you have to fire `insights.chrome.enable.globalFilter()` in console and refresh page. Currently the global filter is allowed only on beta environments and this will set localStorage key to enable it ignoring beta environment. After that you can select any tag and it will prefilter the systems modal for comparision. Basically this ticket https://issues.redhat.com/browse/RHCLOUD-9580

2020-10-07 17:17 UTC, johnsonm325 approved these changes

2020-10-07 17:18 UTC, merged