[DRFT-147] baseline fact modal
RedHatInsights/drift-frontend pull request #440
Opened 2021-02-08 14:21 UTC by opacut

- Add and Delete modals for baseline facts
- TextInput elements
- buttons

2021-02-08 17:24 UTC, johnsonm325 requested changes

2021-02-08 17:24 UTC, johnsonm325 commented on src/SmartComponents/BaselinesPage/EditBaseline/DeleteFactModal/DeleteFactModal.js
> +                ouiaId='delete-fact-modal'
Should we make this consistent? `delete-fact` or `delete-facts` for both.

2021-02-08 17:24 UTC, johnsonm325 commented on src/SmartComponents/BaselinesPage/EditBaseline/DeleteFactModal/DeleteFactModal.js
> +                        ouiaId='cancel-button'
Should we specify what cancel button this is for? `delete-fact-cancel-button`

2021-02-09 13:27 UTC, opacut commented
ammended and rebased

2021-02-09 13:52 UTC, johnsonm325 requested changes

2021-02-09 13:52 UTC, johnsonm325 commented on src/SmartComponents/BaselinesPage/EditBaseline/FactModal/FactModal.js
> +                        ouiaId="save-button"
I should have asked the same question here. This goes for every button like this. Though, `save-button` may be unique. Do we want to call it `fact-modal-save-button`? It's your call really.

2021-02-09 13:52 UTC, johnsonm325 commented on src/SmartComponents/BaselinesPage/EditBaseline/FactModal/FactModal.js
> +                        ouiaId="cancel-button"
`fact-modal-cancel-button`?

2021-02-09 14:31 UTC, opacut commented
changed and rebased

2021-02-09 14:51 UTC, johnsonm325 approved these changes

2021-02-09 14:52 UTC, merged