[DRFT-582] Allow facts and categories to share names
RedHatInsights/drift-frontend pull request #515
Opened 2021-09-09 18:38 UTC by johnsonm325

Because of a discussion in which we decided that a fact and a category can share the same name, we are updating the system-baseline-backend repo with a PR that allows this to happen. This caused some add, deleting and editing of facts, categories and sub facts to work improperly.

This PR allows things to work as usual with a new feature that allows a category and fact to share a name. Facts still can't share names with other facts and categories can't share names with other categories.

## Secure Coding Practices Checklist Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2021-09-09 18:39 UTC, johnsonm325 commented
This PR needs to be merged in conjunction with https://github.com/RedHatInsights/system-baseline-backend/pull/210

2021-09-15 14:58 UTC, jpramos123 commented
Looks like I'm not able to add a subfact to the category

2021-09-15 15:00 UTC, jpramos123 requested changes

2021-09-15 16:38 UTC, jpramos123 commented on src/SmartComponents/BaselinesPage/EditBaselinePage/EditBaseline/EditBaseline.js
Working fine

2021-09-15 16:45 UTC, jpramos123 approved these changes
I made the following tests and it's working fine:

1) Create a fact and category with the same name
2) Create fact, category and subfact with the same name
3) Delete all (fact, category and subfact) at the same
4) Delete each once at a time

Thanks for this PR @johnsonm325

2021-09-15 17:12 UTC, merged