fix(RHINENG-1457): hsp dropdown not displaying hsps
RedHatInsights/drift-frontend pull request #653
Opened 2023-08-09 19:26 UTC by johnsonm325

Description:
I have a system with 4 hsps.  In the comparison modal, when I click on the hsp icon, it reports "There are no historical profiles to display".  See screenshot which shows in the Dev Tools window that the frontend is successfully retrieving the 4 hsps from the backend.

Steps to Reproduce:
1. Navigate to Operations -> Drift -> Comparison
2. Click Add systems or baselines
3. For a system that has hsps, click on the hsp icon. It reports no hsps. *Make sure via the Network tab in dev tools that the hsps fetch actually fetched hsps*

How reproducible: (Always / Intermittent / Random) Always

Actual Results:
No hsps reported

Expected results:
A popup window that allows me to select hsps

## Secure Coding Practices Checklist Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2023-08-09 19:33 UTC, johnsonm325 commented
In light of the urgency of this issue and the fact that I would need to rework a lot of tests, I commented out and skipped a lot of tests. I can come back and redo these tests at a later date.

2023-08-14 11:10 UTC, bastilian commented on src/SmartComponents/HistoricalProfilesPopover/HistoricalProfilesCheckbox/HistoricalProfilesCheckbox.js
> +    const isFirstRender = useRef(true);
@johnsonm325 Can you elaborate on this. That doesn't feel right.

2023-08-23 08:55 UTC, AsToNlele requested changes
This works when there are Historical profiles, but when there are none, I see 404 in the network tab, but in the UI this keeps loading
![image](https://github.com/RedHatInsights/drift-frontend/assets/20592948/fe7428f2-ba67-484e-bfd1-c37728e128e7)

2023-08-23 13:45 UTC, petrblaho commented
I added some notes to the original ticket about the experienced behaviour (could help with testing and finding the issue).

2023-11-08 17:16 UTC, johnsonm325 commented
@AsToNlele you can take another look at this. Your problem should be fixed.

2023-11-21 13:32 UTC, AsToNlele approved these changes
Sorry about the delay,
LGTM :smile:

2023-11-22 19:05 UTC, merged